name: deployment pipeline

on:
  push:
    branches:
           - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  deployment_pipeline:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: npm install
          run: npm install      
        - name: lint
          run: npm run eslint  
        - name: test backend
          run: npm run test 
          env:
            TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        - name: build
          run: npm run build
        - name: e2e tests
          uses: cypress-io/github-action@v2
          env:
            TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
            PORT: 8080
            SECRET: ${{ secrets.SECRET }}
          with:
            command: npm run test:e2e
            start: npm run start-test
            wait-on: http://localhost:8080
        - name: deploy
          if: ${{ github.event_name == 'push' && (contains(toJson(join(github.event.commits.*.message)), '#skip') != true )}} 
          uses: akhileshns/heroku-deploy@v3.11.10
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: "radiant-beach-89717"
            heroku_email: "dan.seliayeu@gmail.com"
            healthcheck: "https://radiant-beach-89717.herokuapp.com/"
            branch: "master"
          env: 
            HD_MONGODB_URI: ${{ secrets.MONGODB_URI }}
            HD_SECRET: ${{ secrets.SECRET }}
        - uses: actions/checkout@v2
        - name: Bump version and push tag
          if: ${{ github.event_name == 'push' && (contains(toJson(join(github.event.commits.*.message)), '#skip') != true )}} 
          uses: anothrNick/github-tag-action@1.33.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
        - name: Discord notification
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          uses: Ilshidur/action-discord@master
          with:
            args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'