name: deployment pipeline

on:
  push:
    branches:
           - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  deployment_pipeline:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: npm install
          run: npm install        
        - name: build
          run: npm run build
        - name: deploy
          if: ${{ github.event_name == 'push' && (contains(toJson(join(github.event.commits.*.message)), '#skip') != true )}} 
          uses: akhileshns/heroku-deploy@v3.11.10
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: "radiant-beach-89717"
            heroku_email: "dan.seliayeu@gmail.com"
            healthcheck: "https://radiant-beach-89717.herokuapp.com/"
            branch: "master"
          env: 
            HD_MONGODB_URI: ${{ secrets.MONGODB_URI }}
            HD_SECRET: ${{ secrets.SECRET }}
            