name: Periodic healtcheck

on:
  schedule:
        - cron:  '0 * * * *'
jobs:
  periodic_healtcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: check health of url
      uses: jtalk/url-health-check-action@v1.4
      with:
        url: "https://radiant-beach-89717.herokuapp.com/"